# use c as catch-all language
language: c

# use containers
sudo: false

# download and unpack
before_install:
  - wget http://www.netlib.org/lapack/lapack-3.6.0.tgz
  - tar xvf lapack-3.6.0.tgz
  - cd lapack-3.6.0

# create the make.inc from example, modify Makefile
install:
  - mv make.inc.example make.inc
  - sed -i -e 's/lib:\ lapacklib\ tmglib /\#lib:\ lapacklib\ tmglib/g' Makefile 
  - sed -i -e 's/#lib:\ blaslib\ variants/\lib:\ blaslib\ variants/g' Makefile 

# build
script:
  - make lib

